---
name: Encode-Punycode
version: 0.99_20091223
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
abstract: Encode plugin for Punycode (S<RFC 3492>)
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
requires:
  Encode: 1
  Net::IDN::Punycode: 0.99
configure_requires:
  Module::Build: 0.35
provides:
  Encode::Punycode:
    file: lib/Encode/Punycode.pm
    version: 0.99_20091223
no_index:
  directory: eg
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
